name: filesystem_dac
description: FS DAC for S5
version: 0.9.0

environment:
  sdk: ^3.0.0

dependencies:
  lib5: ^0.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  hive: ^2.0.4
  path: ^1.8.0
  pool: ^1.5.0
  state_notifier: ^0.7.1
  universal_platform: ^1.0.0+1
  retry: ^3.1.0
  uuid: ^3.0.5
  stash: ^4.0.1
  mime_type: ^1.0.0
  stash_hive: ^4.0.1
  #webdav_client:
  #  git: https://github.com/redsolver/webdav_client.git
  #minio:
  #  git:
  #    url: https://github.com/redsolver/minio-dart.git

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.4
  pedantic: ^1.9.0
