name: filesystem_dac
description: FS DAC for Skynet
version: 0.7.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  blurhash_dart: ^1.0.2
  convert: ^3.0.1
  crypto: ^3.0.1
  exif: ^3.0.0
  hive: ^2.0.4
  id3: ^1.0.1
  image: ^3.0.8
  path: ^1.8.0
  pool: ^1.5.0
  skynet:
    git:
      url: https://github.com/redsolver/skynet.git
      ref: experimental
  sodium: ^1.0.0
  state_notifier: ^0.7.1
  universal_platform: ^1.0.0+1
  flac_metadata:
    git: https://github.com/redsolver/flac_metadata.git
  retry: ^3.1.0
  uuid: ^3.0.5
  stash: ^4.0.1
  mime_type: ^1.0.0
  stash_hive: ^4.0.1
  webdav_client:
    git: https://github.com/redsolver/webdav_client.git
  # cure: ^0.1.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
